/**
 * @file src/utils/colorUtils.js
 * @description Utility functions for generating, manipulating, and displaying colors.
 * This file provides core logic for color generation, contrast calculation, and clipboard operations
 * specific to the Dynamic Color Palette Generator application.
 */

/**
 * Generates a random hexadecimal color code.
 * The color is generated by picking a random number between 0 and 16777215 (FFFFFF in hex)
 * and converting it to a 6-digit hexadecimal string, padded with leading zeros if necessary.
 *
 * @returns {string} A random hex color string in the format "#RRGGBB" (e.g., "#A3B4C5").
 */
export function generateRandomHexColor() {
    // Generate a random integer between 0 and 16777215 (0xFFFFFF)
    const randomColorInt = Math.floor(Math.random() * 16777215);

    // Convert the integer to a hexadecimal string
    let hexColor = randomColorInt.toString(16);

    // Pad with leading zeros to ensure it's always 6 characters long
    // For example, if randomColorInt is 255 (FF), hexColor will be "ff".
    // padStart(6, '0') will turn it into "0000ff".
    hexColor = hexColor.padStart(6, '0');

    // Prepend '#' and convert to uppercase for consistency
    return `#${hexColor.toUpperCase()}`;
}

/**
 * Determines a contrasting text color (black or white) for a given background hex color.
 * This is crucial for ensuring text readability (e.g., hex codes) when displayed
 * on dynamically generated color blocks. It uses the luminance method to assess
 * whether the background color is light or dark.
 *
 * @param {string} hexColor - The hexadecimal color string (e.g., "#RRGGBB" or "RRGGBB").
 * @returns {string} Either '#000000' (black) for light background colors, or '#FFFFFF' (white) for dark background colors.
 */
export function getContrastTextColor(hexColor) {
    // Remove '#' if present to work with the raw hex value
    const cleanHex = hexColor.startsWith('#') ? hexColor.slice(1) : hexColor;

    // Ensure the hex string is 6 characters long (e.g., expand #FFF to #FFFFFF)
    if (cleanHex.length === 3) {
        // Handle shorthand hex codes (e.g., #F00 -> #FF0000)
        const r = cleanHex[0];
        const g = cleanHex[1];
        const b = cleanHex[2];
        return getContrastTextColor(`#${r}${r}${g}${g}${b}${b}`);
    }

    // Parse R, G, B values from the 6-character hex string
    const r = parseInt(cleanHex.substring(0, 2), 16);
    const g = parseInt(cleanHex.substring(2, 4), 16);
    const b = parseInt(cleanHex.substring(4, 6), 16);

    // Calculate luminance (perceived brightness) using the W3C formula.
    // This formula weights the R, G, B components according to human perception.
    // The result is normalized to a 0-1 scale.
    const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;

    // A common threshold for determining light vs. dark is 0.5.
    // If luminance is greater than 0.5, the color is considered "light", so use black text.
    // Otherwise, the color is "dark", so use white text.
    return luminance > 0.5 ? '#000000' : '#FFFFFF';
}

/**
 * Copies the given text string to the user's clipboard.
 * This function utilizes the modern `navigator.clipboard.writeText` API,
 * with a fallback for older browsers or non-secure contexts using a temporary textarea.
 *
 * @param {string} text - The text string to copy to the clipboard.
 * @returns {Promise<void>} A Promise that resolves if the text was copied successfully,
 *                          or rejects with an error if the clipboard operation failed.
 */
export async function copyToClipboard(text) {
    try {
        // Check if the modern Clipboard API is available and supported
        if (navigator.clipboard && navigator.clipboard.writeText) {
            await navigator.clipboard.writeText(text);
            console.info(`Successfully copied "${text}" to clipboard.`);
        } else {
            // Fallback method for environments where Clipboard API is not available
            // (e.g., older browsers, non-HTTPS contexts, or specific browser configurations).
            // This method is less ideal as it involves DOM manipulation and `document.execCommand`
            // which is deprecated but still widely supported for this use case.
            const textarea = document.createElement('textarea');
            textarea.value = text;
            // Make the textarea invisible and outside the viewport to avoid visual disruption
            textarea.style.position = 'fixed';
            textarea.style.opacity = '0';
            textarea.style.left = '-9999px';
            textarea.style.top = '-9999px';
            document.body.appendChild(textarea);
            textarea.focus();
            textarea.select(); // Select the text within the textarea

            // Execute the copy command
            const successful = document.execCommand('copy');
            document.body.removeChild(textarea); // Clean up the temporary textarea

            if (successful) {
                console.warn(`Clipboard API not available, used fallback method to copy "${text}".`);
            } else {
                throw new Error('Fallback copy method failed.');
            }
        }
    } catch (err) {
        console.error('Failed to copy text to clipboard:', err);
        // Re-throw the error to allow calling code to handle it
        throw new Error(`Failed to copy "${text}" to clipboard. Please try again or copy manually.`);
    }
}